'use strict';
const $=s=>document.querySelector(s); const state={screen:'home',lesson:null,deckId:null,page:1,tutorOpen:false,zoom:100,selectedText:'',selectedMessage:null,pending:null,chatPending:null}; let courseData=null;
document.addEventListener('click',event=>{const session=event.target.closest?.('[data-session]');if(session&&!session.disabled){openLesson(session.dataset.session);return;}if(event.target.closest?.('#enter-course'))openLesson('day01');},true);
window.__vlearnEarly=true;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const lessonByDeck=d=>(courseData?.lessons||[]).find(x=>x.deck_id===d);
function showHome(){state.screen='home';state.tutorOpen=false;$('#home-nav').hidden=false;$('#home-screen').hidden=false;$('#lesson-screen').hidden=true;$('#tutor').hidden=true;hideAction();}
function renderSessions(){const items=[['Buổi 1: Day01','day01'],['Buổi 2: DAY02','day02'],['Buổi 3: DAY03',null],['Buổi 4: DAY04',null],['Buổi 5: DAY05',null],['Buổi 6: DAY06',null]];$('#session-list').innerHTML=items.map(([name,id],i)=>id?`<a class="session ${id?'available':'unavailable'}" href="?lesson=${id}" data-session="${id}"><span class="radio">▶</span><strong>${name}</strong><small>${i===0?'ĐANG HỌC':'SẴN SÀNG'}</small></a>`:`<button class="session unavailable" disabled><span class="radio">○</span><strong>${name}</strong><small>Chưa có data demo</small></button>`).join('');}
async function loadCourse(){try{const r=await fetch('/api/course-data');courseData=await r.json();}catch{courseData={lessons:[{id:'day01',title:'Day01 · AI & LLM Foundation',deck_id:'d1',pages:29},{id:'day02',title:'Day02 · Xác định bài toán cho AI',deck_id:'d2',pages:29}]};}renderSessions();}
function openLesson(id,page=1){const lesson=(courseData?.lessons||[]).find(x=>x.id===id);if(!lesson)return;state.screen='lesson';state.lesson=lesson;state.deckId=lesson.deck_id;state.page=page;state.tutorOpen=false;state.zoom=100;$('#home-nav').hidden=true;$('#home-screen').hidden=true;$('#lesson-screen').hidden=false;$('#tutor').hidden=true;$('#lesson-heading').textContent=`Bài ${id==='day01'?'1':'2'} · ${id.toUpperCase()}`;renderSlideItems();loadSlide();}
function renderSlideItems(){$('#slide-items').innerHTML=(courseData?.lessons||[]).map(l=>`<button class="lesson-item ${l.id===state.lesson.id?'active':''}" data-lesson="${l.id}"><span class="slide-icon">▱</span><span>${esc(l.title)}</span>${l.id===state.lesson.id?'<b>Đang học</b>':''}</button>`).join('');document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));}
function loadSlide(){const total=state.lesson.pages;state.page=Math.max(1,Math.min(total,state.page));const image=$('#slide-image');$('#slide-loading').hidden=false;image.hidden=true;image.src=`/api/slide-image?deck_id=${encodeURIComponent(state.deckId)}&page=${state.page}`;image.onload=()=>{$('#slide-loading').hidden=true;image.hidden=false;};image.onerror=()=>{$('#slide-loading').textContent='Không tải được slide.';};$('#slide-number').textContent=state.page;$('#slide-total').textContent=total;$('#prev-slide').disabled=state.page<=1;$('#next-slide').disabled=state.page>=total;$('#lecturer-note').textContent=`Trang ${state.page} · ${state.lesson.title}`;document.title=`${state.lesson.title} · Trang ${state.page}`;const c=$('.context-label');if(c)c.textContent=`Đang mở: ${state.lesson.title} · trang ${state.page}`;}
function changePage(d){state.page=Math.max(1,Math.min(state.lesson.pages,state.page+d));loadSlide();}
function openTutor(){state.tutorOpen=true;$('#tutor').hidden=false;initialChat();$('#chat-input').focus();} function closeTutor(){state.tutorOpen=false;$('#tutor').hidden=true;hideAction();}
function initialChat(){if(!state.tutorOpen)return;state.chatPending=null;$('#conversation').innerHTML=`<p class="context-label">Đang mở: ${esc(state.lesson?.title||'')} · trang ${state.page}</p><div class="message assistant"><div class="message-label">✦ Trợ giảng AI</div><p>Xin chào DŨNG! Mình có thể giải thích nội dung các slide đang mở.</p><p class="selection-hint">Hãy đặt câu hỏi về bài học để bắt đầu.</p></div>`;}
function appendMessage(text,type='assistant'){const n=document.createElement('div');n.className=`message ${type}`;if(type==='assistant')n.innerHTML='<div class="message-label">✦ Trợ giảng AI</div>';const p=document.createElement('p');p.className='answer-text';p.textContent=text;n.append(p);$('#conversation').append(n);return n;}
function closeSearch(){$('#search-results').hidden=true;$('#lesson-list').hidden=false;}
async function searchSlides(query){$('#lesson-list').hidden=true;$('#search-results').hidden=false;$('#search-results').innerHTML='<p class="empty-state">Đang tìm trong slide thật…</p>';try{const r=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const data=await r.json();if(!r.ok)throw Error(data.message||'Không tìm được slide.');const results=data.results||[];$('#search-results').innerHTML=`<div class="results-heading"><span>${results.length} kết quả · ${esc(data.mode)}</span><button id="close-search">Đóng ×</button></div>`+(results.length?results.map((x,i)=>`<article class="result-card"><h3>${esc(x.lesson)}</h3><span class="slide-ref">Trang ${x.page} · điểm ${x.score}</span><p>${esc(x.snippet)}</p><button data-result="${i}">Mở slide ↗</button></article>`).join(''):'<p class="empty-state">Chưa tìm thấy slide phù hợp. Thử từ khóa khác.</p>');$('#close-search').onclick=closeSearch;document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>openSearchResult(results[+b.dataset.result]));}catch(e){$('#search-results').innerHTML=`<p class="empty-state">${esc(e.message)}</p>`;}}
function openSearchResult(result){const l=lessonByDeck(result.deck_id);if(!l)return;closeSearch();openLesson(l.id,result.page);}
function hideAction(){$('#explain-selection').hidden=true;state.selectedText='';state.selectedMessage=null;}
function inspectSelection(){const s=getSelection();if(!s||s.isCollapsed||!s.rangeCount)return hideAction();const range=s.getRangeAt(0),msg=range.startContainer.parentElement?.closest('.message.assistant');if(!msg||msg!==range.endContainer.parentElement?.closest('.message.assistant'))return hideAction();state.selectedText=s.toString().trim();state.selectedMessage=msg;if(!state.selectedText||state.pending)return hideAction();const a=$('#explain-selection'),r=range.getBoundingClientRect();a.hidden=false;a.style.left=`${Math.max(8,r.left)}px`;a.style.top=`${Math.max(8,r.top-a.offsetHeight-8)}px`;}
async function explainSelection(){if(!state.selectedText||!state.selectedMessage||state.pending)return;const originalAnswer=state.selectedMessage.textContent.trim();if(!originalAnswer.includes(state.selectedText))return hideAction();const node=appendMessage('Đang giải thích đoạn bạn chọn…');node.setAttribute('aria-busy','true');const controller=new AbortController();state.pending=controller;const selected=state.selectedText;hideAction();try{const r=await fetch('/api/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deck_id:state.deckId,page:state.page,original_question:'',original_answer:originalAnswer,selected_text:selected}),signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.message||'Không gọi được AI.');const field={explain:'explanation',clarify:'question',no_grounding:'message',refuse:'message'}[d.action];if(!field||!d[field])throw Error('Phản hồi AI không hợp lệ.');node.querySelector('p').textContent=d[field];}catch(e){node.querySelector('p').textContent=e.message||'Không gọi được AI.';}finally{node.removeAttribute('aria-busy');state.pending=null;}}
const on=(selector,event,handler)=>{const element=$(selector);if(element)element.addEventListener(event,handler);};
window.__vlearnWired=true;
on('#home-brand','click',e=>{e.preventDefault();showHome();});
on('#enter-course','click',()=>openLesson('day01')); on('#back-home','click',showHome); on('#ask-ai','click',openTutor); on('#close-tutor','click',closeTutor); on('#prev-slide','click',()=>changePage(-1)); on('#next-slide','click',()=>changePage(1));
on('#zoom-out','click',()=>{state.zoom=Math.max(75,state.zoom-10);$('#zoom-label').textContent=state.zoom+'%';$('#slide-image').style.transform=`scale(${state.zoom/100})`;}); on('#zoom-in','click',()=>{state.zoom=Math.min(150,state.zoom+10);$('#zoom-label').textContent=state.zoom+'%';$('#slide-image').style.transform=`scale(${state.zoom/100})`;});
const toggleNotes=()=>{$('#personal-note').hidden=!$('#personal-note').hidden;}; on('#note-button','click',toggleNotes); on('#notebook','click',toggleNotes); on('#slides-toggle','click',()=>{$('#slide-items').hidden=!$('#slide-items').hidden;});
on('#search-form','submit',e=>{e.preventDefault();const q=$('#search-input').value.trim();if(q)searchSlides(q);}); on('#search-input','input',()=>{if(!$('#search-input').value.trim())closeSearch();}); on('#explain-selection','click',explainSelection); on('#conversation','mouseup',()=>setTimeout(inspectSelection,0)); on('#conversation','keyup',inspectSelection);
on('#chat-input','input',e=>$('#send-message').disabled=!e.target.value.trim()||Boolean(state.chatPending));
on('#chat-form','submit',async e=>{e.preventDefault();const question=$('#chat-input').value.trim();if(!question||state.chatPending||!state.lesson)return;appendMessage(question,'user');$('#chat-input').value='';$('#send-message').disabled=true;const pending=appendMessage('Đang suy nghĩ…');pending.setAttribute('aria-busy','true');const controller=new AbortController();state.chatPending=controller;const timeout=setTimeout(()=>controller.abort(),60000);try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({deck_id:state.deckId,page:state.page,question}),signal:controller.signal});const data=await response.json();if(!response.ok)throw Error(data.message||'Không gọi được AI. Hãy thử lại.');if(typeof data.answer!=='string'||!data.answer.trim())throw Error('Phản hồi AI không hợp lệ.');pending.querySelector('p').textContent=data.answer;}catch(error){pending.querySelector('p').textContent=error.name==='AbortError'?'Yêu cầu đã hết thời gian. Hãy thử lại.':error.message||'Không gọi được AI. Hãy thử lại.';}finally{clearTimeout(timeout);pending.removeAttribute('aria-busy');if(state.chatPending===controller)state.chatPending=null;$('#send-message').disabled=!$('#chat-input').value.trim();}}); on('#new-chat','click',initialChat);
document.addEventListener('click',event=>{const session=event.target.closest('[data-session]');if(session&&!session.disabled){openLesson(session.dataset.session);return;}if(event.target.closest('#enter-course'))openLesson('day01');},true);
loadCourse().then(()=>{const lesson=new URLSearchParams(location.search).get('lesson');if(lesson)openLesson(lesson);else showHome();});
